local status_ok, lsp = pcall(require, 'lsp-zero')
if not status_ok then return end

lsp.preset('recommended')
lsp.on_attach(function(client, bufnr)
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, {buffer = bufnr})
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, {buffer = bufnr})
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, {buffer = bufnr})
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, {buffer = bufnr})
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, {buffer = bufnr})
  vim.keymap.set('n', 'gl', vim.diagnostic.open_float, {buffer = bufnr})
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, {buffer = bufnr})
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, {buffer = bufnr})
end)
lsp.setup()
